name: Make Everything Selfie

on:
  push:
    paths-ignore:
    - '**.md'
    - '**.txt'
    - 'docs'
    - 'AUTHORS'
    - 'LICENSE'
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.txt'
    - 'docs'
    - 'AUTHORS'
    - 'LICENSE'
  schedule:
    # trigger fridays at 12am
    - cron: '0 0 * * 5'

jobs:
  make-all-on-linux:
    name: Make all of selfie on Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Make all
      run: make -j -O all
    - name: Use Python 3.7.x
      uses: actions/setup-python@v1
      with:
        python-version: "3.7.x"
    - name: Run autograder baseline
      run: make grade

  make-all-on-macos:
    name: Make all of selfie on macOS
    runs-on: macos-latest

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Make all
      run: make -j all
    - name: Use Python 3.7.x
      uses: actions/setup-python@v1
      with:
        python-version: "3.7.x"
    - name: Run autograder baseline
      run: make grade

  make-all-on-windows:
    name: Make all of selfie on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Make all
      env:
        CC: gcc
      run: make -j -O all
    # python3 does not work here

  make-everything-on-docker:
    name: Make everything of selfie on docker
    runs-on: ubuntu-latest

    # usage:
    #
    # - pull docker image: docker pull cksystemsteaching/selfie
    # - run command:       docker run --platform linux/amd64 -v cksystemsteaching/selfie command
    # - run interactive:   docker run --platform linux/amd64 -it cksystemsteaching/selfie
    # - run on my selfie:  docker run --platform linux/amd64 -it -v /myselfie:/opt/myselfie cksystemsteaching/selfie

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t cksystemsteaching/selfie .
    - name: Make everything
      run: |
        docker run cksystemsteaching/selfie make -j -O everything
        docker run cksystemsteaching/selfie make pythons
    - name: Deploy docker image
      run: |
        docker run cksystemsteaching/selfie make clean
        echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push cksystemsteaching/selfie
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'cksystemsteaching/selfie' }}